# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Project Name
description:      'This is where you put your project short description'

#Github Pages site and baseurl
url:              #https://michaellgraves.github.io
baseurl:          #/project-blog-template

#Local site
url:              http://localhost:4000

#Google Analytics tracking id
analytics:        UA-423848-5

author:
  name:           'You Name'
  twitter:        https://twitter.com/yourtwitterhandle

gems:             [jekyll-paginate, jekyll-gist]
